### ISSUE TITLE
Menu for visualisation section is unclear 

### ISSUE THREAD

**Issue by ptopa** [aghinz2015/foram-3d#27]
In my opinion menu on right side of visualisation screen is unclear and difficult to use. The main problem is in lack of distinction between various UI components. Buttons that refresh model (in my opinion should be emphasized) are lost between other components. I think we need something what provide information how to use these components, i.e. graphical signs...

**Comment by ptopa** [comment]
I noticed one more thing. Menu has to sections: a) structure analyzer and b) morphology. They present the same information.

**Comment by ptopa** [comment]
I attach my idea of menu structure: [menu-propozycja.pdf](https://github.com/aghinz2015/foram-3d/files/77724/menu-propozycja.pdf). What do you think?

**Comment by bzurkowski** [comment]
@ptopa I have some suggestions and questions for clarification:
1. What is the exact purpose of option `Reset parameters`?
2. What happend with options `Evolve` and `Regress`. Should they be completely removed from visualizations's toolbar?
3. Old `Morphology` section becomes `Morphometrics`?
4. When user starts from `Browser` section and clicks `Visualize` button without selecting record from the table, they ends with blank simulation scene. User is able to set genotype and then perform simulation - user generates model from scratch instead of refreshing already existing object. I suggest label `Generate model` over `Refresh model`?

**Comment by bzurkowski** [comment]
1. Where does `Number of chambers` go? Currently it has been moved to `Genotype` section.

**Comment by ptopa** [comment]
@bzurkowski :
ad 1: Redraw model with parameters exactly as it was in record from DB. In other words any modifications introduced by user in Genotype section are cancelled.
ad 2: Remove
ad 3: Yes 
ad 4: I agree.

ad 1: I think it is good idea to have "No of chambers" in Genotype section.

**Comment by bzurkowski** [comment]
@ptopa New version of visualization's toolbar has been deployed in production environment (http://mongo.icsr.agh.edu.pl/). Please verify the results.
